### ISSUE TITLE
Duplicated routing param and query string param?

### ISSUE THREAD

**Issue by Preetam** [VividCortex/siesta#34]
What if someone has a `/foo/:name/bar/` route and wants to have a `name` query string key, e.g. `/foo/someName/bar/?name=otherName`?

`name` would be set to `otherName` in the parameters when you might expect `someName`.

We should add a comment on this to the docs.

**Comment by leifmadsen** [comment]
I actually was looking through the examples and thinking the same thing. I was wondering how you might send multiple arguments and parse them.

For example (simpler than you have noted):

`/:name?foo=1&bar=baz`

**Comment by Preetam** [comment]
You'd just add new params, just like the flag package. Is something not working for you?

**Comment by leifmadsen** [comment]
@Preetam nah, I just haven't gotten in there yet to figure out exactly how to do it, and it wasn't totally obvious in the few minutes I spent looking at examples last night :)

**Comment by Preetam** [comment]
Gotcha. Yeah, I think there should probably be more clarity in the documentation or the examples.
