### ISSUE TITLE
Update README with examples and documentation

### ISSUE THREAD

**Issue by Preetam** [VividCortex/siesta#37]
Maybe a walkthrough of the [existing examples](https://github.com/VividCortex/siesta/tree/cfab5fa8759d3ab6b20e9e068fb09a1db0879831/examples) would be enough.

**Comment by leifmadsen** [comment]
Would definitely be useful. The authentication example looks fairly complete, but would be nice to see how you could keep the state outside of the code itself. I think what you have currently in the examples folder would be good for a set of a few blog posts.
