### ISSUE TITLE
how to get query parameters ?

### ISSUE THREAD

**Issue by cloudtrends** [VividCortex/siesta#43]
hi,

I can run sample examples , such as 

http://x.x.x.x/greeting/hello

I want get parameters after ? , such as:

http://x.x.x.x/greetings/?name=hello 

Is siesta support this format ?

thanks.

**Comment by PreetamJinka** [comment]
Yes. We support these the same way we support the URL parameters. Take a look at the [params example](https://github.com/VividCortex/siesta/blob/master/examples/params/main.go).

I'm going to assume you're expecting a `string`.

```go
func(c siesta.Context, w http.ResponseWriter, r *http.Request) {
	var params siesta.Params

	// The second argument is the default value for the parameter.
	name := params.String("name", "", "The name of the person to greet")
	if err := params.Parse(r.Form); err != nil {
		// do something
		return
	}
}
```

**Comment by cloudtrends** [comment]
hi

@PreetamJinka

Actually , after my test :
first use:

http://localhost:8080/greet/chunfeng

the browser show as my expected:   Hello, chunfeng!

But , when I use the url as below format : 

http://localhost:8080/greet/?name=chunfeng

The browser show that , 
 404 page not found .

Is there somethings I missed ?

thanks.

**Comment by PreetamJinka** [comment]
You would use two routes for that. `/greet/:name` and `/greet`.

**Comment by cloudtrends** [comment]
you are right !

thanks , and I am close this issue now.

**Comment by PreetamJinka** [comment]
No problem! Let us know if you need any more help.
