### ISSUE TITLE
Rethink param "show docs"

### ISSUE THREAD

**Issue by PreetamJinka** [VividCortex/siesta#8]
We should be able to check for `showdocs=true` in a middleware handler, if that makes sense.

**Comment by PreetamJinka** [comment]
At this point, I think there's enough in the package itself to support this without any changes.

Here's what one could do:

1. Check if the user requested usage documentation at the beginning of a chain.
2. Create a map to hold the documentation for all of the parameters.
3. Run through the chain. Each handler would update the documentation map using the output from [`params.Usage`](https://github.com/VividCortex/siesta/blob/489a9fe4a2fb860664050591ff0c0f8ad1b3d36a/params.go#L77), since each handler can have its own set of parameters. It's important to make sure each handler *only* updates the documentation map and does nothing else.
4. Send the output back to the user

On a related note, I'm not really a fan of having the magical [`showdocs` parameter](https://github.com/VividCortex/siesta/blob/489a9fe4a2fb860664050591ff0c0f8ad1b3d36a/params.go#L30-L35). I think we should get rid of that. The rest can be done with simple context variables and params.Usage().

Ping @gkristic.

**Comment by gkristic** [comment]
Sounds good to me. (For future reference: see also [this](https://github.com/VividCortex/customers-service/issues/74#issuecomment-106860901).)

**Comment by PreetamJinka** [comment]
We know how to do this now.
